name: Combined CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: All tests
    runs-on: ubuntu-latest
    steps:

      #
      #     Setting up environment
      #
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up MemCached
        uses: niden/actions-memcached@v7

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      #
      #     Building Backend etc
      #

      - name: Build & Test Backend
        run: |
          go get -v -t -d ./...
          go test -v  ./...
          go build -v .
        working-directory: 'service/'
