name: Combined CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: All tests
    runs-on: ubuntu-latest
    environment: Default
    steps:

      #
      #     Setting up environment
      #
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      #
      #     Building Backend etc
      #

      - name: Build & Test Backend
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          MASTER_KEY: "very_secret_master_key"
          TIMING: "yes"
        run: |
          go get -v -t -d ./...
          go build -v .
          go test -v  ./...
        working-directory: './'

      - name: Run Backend service
        env:
          MASTER_KEY: TEST_MASTER_KEY
          UPLOAD_KEY: TEST_UPLOAD_KEY
          ROOT_DIR: /tmp
          STATIKA_PORT: 9191
          TIMING: "yes"
        run: ./statika 1>/dev/null 2>/dev/null &
        working-directory: './'

      - name: Typescript API step
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test:ci
        working-directory: 'typescript/'
