name: Combined CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: All tests
    runs-on: ubuntu-latest
    steps:

      #
      #     Setting up environment
      #
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up MemCached
        uses: niden/actions-memcached@v7

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      #
      #     Building Backend etc
      #

      - name: Build & Test Backend
        run: |
          go get -v -t -d ./...
          go test -v  ./...
          go build -v .
        working-directory: 'service/'

      - name: Run Backend service
        env:
          MEMCACHED_HOST: localhost
          MASTER_KEY: TEST_MASTER_KEY
          UPLOAD_KEY: TEST_UPLOAD_KEY
          ROOT_DIR: /tmp
          STATIKA_PORT: 8080
        run: ./service 1>/dev/null 2>/dev/null &
        working-directory: 'service/'

      - name: Typescript API step
        run: |
          npm install
          npm run build
          npm run test:ci
        working-directory: 'api/typescript/'

