name: Docker publisher

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build containers
    runs-on: ubuntu-latest
    steps:

      #
      #     Setting up the environment
      #
      - name: Check out code into the module directory
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Statika backend
        run: docker build -t raver119/statika:latest .
        working-directory: './'

      - name: Push to Docker
        run: docker push raver119/statika:latest
